- op: add
  path: /jobs/test/steps/3
  value:
    name: Download ironoxide-java release
    uses: robinraju/release-downloader@v1.6
    with:
      repository: "IronCoreLabs/ironoxide-swig-bindings"
      fileName: "libironoxide_java.so"
      latest: true
- op: test
  path: /jobs/test/steps/4/name
  value: build and test
- op: replace
  path: /jobs/test/steps/4
  value:
    name: build and test
    run: LD_LIBRARY_PATH=./ sbt scalafmtCheckAll scalastyle test
