addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"           % "3.9.15")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"                % "2.1.1")
addSbtPlugin("com.github.gseitz" % "sbt-release"            % "1.0.13")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"           % "2.5.0")
addSbtPlugin("org.scalastyle"    %% "scalastyle-sbt-plugin" % "1.0.0")
