name: Scala CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 14 * * 1

jobs:
  invoke:
    name: Scala CI
    uses: IronCoreLabs/workflows/.github/workflows/scala-ci.yaml@scala-ci-v0
    with:
      download_release_binary_repo: IronCoreLabs/ironoxide-swig-bindings
      download_release_binary_name: libironoxide_java.so
      coverage: false
    secrets: inherit
