name: Scala CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  LD_LIBRARY_PATH: "./"

jobs:
  invoke:
    name: Scala CI
    uses: IronCoreLabs/workflows/.github/workflows/scala-ci.yaml@scala-ci
    with:
      download_release_binary_repo: IronCoreLabs/ironoxide-swig-bindings
      download_release_binary_name: libironoxide_java.so
      coverage: false
    secrets: inherit
